services:
  ml_worker:
    build: ./ml_node
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://[IP_ADDRESS]/app
      API_TCP_ADDRESS: [IP_ADDRESS]
    deploy:
      mode: replicated
      replicas: 3